bot:
  accessToken: 9722fe77-9acf-46cf-8df0-d05c77e3d152
  helloImageUrl: "https://media.giphy.com/media/ICOgUNjpvO0PC/source.gif"
  byeImageUrl: "https://media.giphy.com/media/EE185t7OeMbTy/source.gif"